name: Spread the Word!

env: 
  APPLICABLE_BRANCH: feature/actions-testing

on: 
  push: 
    branches:
      - feature/actions-testing

jobs: 
  setup: 
    name: Set this bitch up
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2

      - name: download dependencies
        run: npm install

      - name: Send email
        uses: dawidd6/action-send-mail@v2.5.0
        env: 
          DOCKER_OUTPUT: 
        with: 
          server_address: ${{secrets.MAIL_SERVER}}
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: A GitHub action from ${GITHUB_REF} in ${{GITHUB_REPOSITORY}} was run
          body: |
            That's all we got for now chief. 
            You wanted an actual email? HTML? Markdown? 
            Yikes dawg
            Actually here's something: 
            ${{GITHUB_ACTION}}
          to: ncotlar@macrofab.com
          from: Nosson via GitHub Actions